name: 'Git Version'
description: 'Output a deterministic semantic version'
inputs:
outputs:
  git_version:
  git_author:
  git_author_email:
  git_branch:
  git_branch_clean:
  git_commit:
  git_commit_short:
  git_commit_timestamp:
  git_commit_epoch:
  git_commit_message:
  git_ag:
  git_tag_long:
  git_version:
    description: 'The version based on the git metadata'
runs:
  using: 'node12'
  main: 'dist/index.js'
