name: Publish
on:
  push:
    tags:
      - v*

jobs:
  npm-packages:
    name: Publish NPM Packages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Get Git Metadata
      uses: ./
    - name: Package
      env:
        PACKAGE_VERSION: ${{steps.get-git-metadata.output.git_version}}
      run: |
        npm install
        npm version ${PACKAGE_VERSION}
        npm run package
    - name: Publish
      env:
        NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
      run: |
        echo '//registry.npmjs.org/:_authToken=${NPMJS_TOKEN}' >> .npmrc
        npm publish --registry https://npm.pkg.github.com