name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test-v1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: git_metadata
      uses: ./
    - env:
        version: ${{steps.git_metadata.outputs.git_version}}
      run: |-
        echo "This is my version: ${version}"

  # test action works running from the graph
  test-v2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #with:
      #  # Required to get the full history for git_metadata
      #  fetch-depth: 0
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - id: git_metadata
      uses: ./
    - env:
        version: ${{steps.git_metadata.outputs.git_version}}
      run: |-
        echo "This is my version: ${version}"